KiizanKiizan/manene

- package.json
- yarn.lock
下記ライブラリのインストールが完了
- MUI
- playwright
- React Query
- axios
- axios-case-converter
> 5 ライブラリのインストール

- .github/workflows/preview.yaml
- .github/workflows/production.yaml
vercelの自動デプロイをできるように、GIthub Actionsを使って設定。
また、リポジトリにpushするか、PRがマージされるたびに、GIthub上にVercelのプレビューデプロイのURLが表示される。
参考記事: https://zenn.dev/ttskch/articles/691fb62fbb6b1b
> 1 自動デプロイを実行できるようにする

- .eslintrc.json
- .husky/pre-commit
- app/layout.tsx
- package.json
- yarn.lock
- eslint, Husky, lint-stagedを導入した(参考記事 - https://zenn.dev/resistance_gowy/articles/91b4f62b9f48ec)
- eslintの設定はここから引用(https://kiizan-kiizan.atlassian.net/wiki/spaces/KK/pages/142409747/front#:~:text=return%20%3C%3E%7BuserName%7D%3C/%3E%0A%20%20%20%20%20%20%20%20%7D-,%E3%81%9D%E3%81%AE%E4%BB%96,-console.log()%E3%82%84)
Closes #2
> 2 コミット時にlinterを適用する

- .eslintrc.json
> fix: 未使用変数とany型をwarningniする

- .env.development
- .env.production
- app/page.tsx
- next.config.js
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- yarn.lock
@kotaesaki @kojikojiXX @ytsumori 本番環境でsentryでエラーが検知されるかの動作確認したいのでmainにマージします！
> Release/7 エラーを検知できるようにする

- app/page.tsx
> test: 環境変数確認テスト

- .env.production
- app/page.tsx
- next.config.js
- package.json
- sentry.client.config.ts
- sentry.edge.config.ts
- sentry.server.config.ts
- yarn.lock
> feat: エラー通知テスト

- app/api/coorde_pick/useCoordePicksIndex.ts
- app/components/common/Image/expandable-image.tsx
- app/components/common/Item/item-card.tsx
- app/components/common/Item/item-info-card.tsx
- app/components/coorde-pick/coorde-pick-list.tsx
> Feature/11 29 コーデピックcoordpicklisttsx作成

- app/components/common/pages/error-page.tsx
- app/components/common/pages/loading-page.tsx
- app/components/coorde-pick/chart-item-fetcher.tsx
> Feature/11 30 コーデピックchartitemfetchertsx作成

- app/api/coorde_pick/lost_articles/useLostArticlesConfirm.ts
- app/api/coorde_pick/lost_articles/useLostArticlesCreate.ts
- app/api/usePostRequest.ts
> Feature 62 74 忘れ物apiフックス作成

- .vscode/extensions.json
- app/api/coorde_pick/lost_articles/useLostArticlesConfirm.ts
- app/components/lost_articles/lost-articles-dialogs.tsx
> Feature/61 78 lostarticlesdialogs作成

- app/components/lost_articles/lost_articles-form.tsx
> feat: LostArticlesFormの作成

- app/api/item_detail/getItemsShow.ts
> feat: アイテムの詳細情報を取得する関数を作成

- app/api/item_detail/getItemsShow.ts
- app/components/common/Image/expandable-image.tsx
- app/components/common/Item/item-detail-card-container.tsx
- app/components/common/Item/item-detail-card.tsx
- app/item_detail/[id]/page.tsx
> Feature/90 96 アイテム詳細表示itemdetailcardの作成

- app/api/item-location/useItemLocationsItemScan.ts
- app/api/item-location/useItemLocationsMove.ts
- app/api/item-location/useItemsShow.ts
- app/api/usePatchRequest.ts
>  feat: APIフックスの作成

- app/api/item-location/useItemLocationsItemScan.ts
- app/components/common/Item/item-list.tsx
- app/components/common/Item/item-mini-card.tsx
- app/components/item_location/item-list.tsx
> Feature/61/107 itemlist作成

- app/api/item_status/getOptionsIndex.ts
- app/api/item_status/useItemsBulkUpdateStatus.ts
- app/api/item_status/useItemsValidateBulkUpdateStatus.ts
> feat: API関数作成

- app/components/common/Item/item-detail-card.tsx
- app/components/common/barcode/barcode-input-dialog.tsx
- app/page.tsx
- tests/item_detail/item_detail.spec.ts
> Feature/90/118 アイテム詳細画面のテスト実装2

- app/api/cleaning-costs/getCreaningCostsChoice.ts
- app/cleaning_costs/layout.tsx
- app/cleaning_costs/page.tsx
- app/components/cleaning-costs/cleaning-costs-container.tsx
- app/page.tsx
> CleaningCostsContainer PR再度

- app/_components/size_measurements/[id]/size-measurements-list.tsx
> feat: SizeMeasurementsListの作成

- app/_components/size_measurements/[id]/Size-measurements-edit-form.tsx
- app/_components/size_measurements/[id]/size-measurement-edot-form.tsx
- app/_components/size_measurements/[id]/size-measurements-list-item.tsx
要件がわかるURLを貼り付けてください
https://github.com/KiizanKiizan/Manene/issues/264
SizeMeasurementsEditFormの作成
JiraのURLを貼り付けてください
https://kiizan-kiizan.atlassian.net/browse/LEEAP-4967
| before                                     | after                                      |
| ------------------------------------------ | ------------------------------------------ |
| <img width="250" alt=""> | <img width="250" alt=""> |
> Feature/263/276 sizemeasurementseditform作成
